name: OBS release

on:
  workflow_call:
    inputs:
      update_changelog:
        type: boolean
        required: false
        default: false
        description: Boolean that indicates if the .changes (changelog) file should be updated.
      obs_project:
        type: string
        required: true
        description: The OBS project to commit changes to.    
    secrets:
      OBS_USER:
        required: true
      OBS_PASS:
        required: true

concurrency: ${{ github.workflow }}-${{ inputs.obs_project }}




jobs:
  obs-commit:
    name: Commit to OBS project ${{ matrix.obs_project_target }}
    runs-on: ubuntu-24.04
    container:
      image: ghcr.io/trento-project/continuous-delivery:main
      env:
        OBS_PROJECT: ${{ inputs.obs_project }}
        AUTHOR_EMAIL: trento-developers@suse.com
        DEST_FOLDER: "/tmp/osc_project"
        FOLDER: packaging/suse
        PACKAGE: supportutils-plugin-trento
      options: -u 0:0
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Configure OSC
        env:
          OBS_USER: ${{ secrets.OBS_USER }}
          OBS_PASS: ${{ secrets.OBS_PASS }}          
        run: |
          mkdir -p $HOME/.config/osc
          cp /home/osc/.config/osc/oscrc $HOME/.config/osc
          /scripts/init_osc_creds.sh
      - name: Prepare _service file with version details
        run: |
          git config --global --add safe.directory /__w/support/support
          VERSION=$(/scripts/get_version_from_git.sh)
          PACKAGE_FOLDER=$FOLDER/$PACKAGE
          sed -i 's~%%REVISION%%~${{ github.sha }}~' $PACKAGE_FOLDER/_service && \
          sed -i 's~%%VERSION%%~'"${VERSION}"'~' $PACKAGE_FOLDER/_service
      - name: Prepare OBS package
        env:
          OBS_PROJECT: ${{ vars.OBS_PROJECT }}
        run: |
          PACKAGE_FOLDER=$FOLDER/$PACKAGE
          osc checkout $OBS_PROJECT $PACKAGE -o $DEST_FOLDER
          cp $PACKAGE_FOLDER/_service $DEST_FOLDER
          cp $PACKAGE_FOLDER/${PACKAGE}.spec $DEST_FOLDER
          rm -fv $DEST_FOLDER/*.tar.gz
          pushd $DEST_FOLDER
          osc service manualrun
      - name: Prepare .changes file
        if: github.event_name == 'release'
        run: |
          CHANGES_FILE=${PACKAGE}.changes
          TAG=${{ steps.latest-tag.outputs.tag }}
          /scripts/gh_release_to_obs_changeset.py ${{ github.repository }} -a trento-developers@suse.com -t $TAG -f $DEST_FOLDER/$CHANGES_FILE
      - name: Commit on OBS
        run: |
          pushd $DEST_FOLDER
          osc ar
          osc commit -m "GitHub Actions automated update to reference ${{ github.sha }}"