name: CD to SUSE OBS Rolling
concurrency: cd-obs-${{ github.ref }}
on:
  push:
    tags-ignore:
      - "*"
    branches:
      - "main"
    paths-ignore:
      - 'VERSION'    
  workflow_dispatch:

jobs:        
  obs-rolling:
    name: Update OBS package
    uses: ./.github/workflows/obs-sync.yaml
    secrets: inherit
    with:
      update_changelog: false
      obs_project: ${{ env.OBS_PROJECT_ROLLING }}