name: CD to SUSE OBS Rolling
concurrency: cd-obs-${{ github.ref }}
on:
  push:
    tags-ignore:
      - "*"
    branches:
      - "main"
    paths-ignore:
      - 'VERSION'    
  workflow_dispatch:

jobs:
  check-version:
    name: Check for VERSION changes
    runs-on: ubuntu-latest
    outputs:
      skip: ${{ steps.check.outputs.skip }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Check if VERSION file was modified
        id: check
        run: |
          if git diff --name-only HEAD^ HEAD | grep -q '^VERSION$'; then
            echo "skip=true" >> $GITHUB_OUTPUT
          else
            echo "skip=false" >> $GITHUB_OUTPUT
          fi

  obs-sync-rolling:
    name: Update OBS package
    needs: check-version
    if: needs.check-version.outputs.skip == 'false'
    uses: ./.github/workflows/obs.yaml
    secrets: inherit
    with:
      update_changelog: false
      obs_project: ${{ vars.OBS_PROJECT_ROLLING }}
