name: CD to SUSE OBS Rolling

on:
  push:
    tags-ignore:
      - "*"
    branches:
      - "main"
    paths-ignore:
      - "VERSION" 
      - "CHANGELOG.md"
  workflow_dispatch:

concurrency: ${{ github.workflow }}

jobs:
  check-version-modified:
    name: Check for VERSION changes
    runs-on: ubuntu-latest
    outputs:
      version_modified: ${{ steps.check.outputs.version_modified }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Check if VERSION file was modified
        id: check
        run: |
          if git diff --name-only HEAD^ HEAD | grep -q '^VERSION$'; then
            echo "version_modified=true" >> $GITHUB_OUTPUT
          else
            echo "version_modified=false" >> $GITHUB_OUTPUT
          fi

  obs-sync-rolling:
    name: Update OBS package
    needs: check-version-modified
    if: needs.check-version-modified.outputs.version_modified == 'false'
    uses: ./.github/workflows/obs.yaml
    secrets: inherit
    with:
      obs_project: ${{ vars.OBS_PROJECT_ROLLING }}
