name: Continous Delivery to SUSE OBS Rolling Project
concurrency: cd-obs-${{ github.ref }}
on:
  push:
    tags-ignore:
      - "*"
    branches:
      - "main"
    paths-ignore:
      - 'VERSION'    
  pull_request:
  workflow_dispatch:

jobs:
  obs-cd:
    name: Update OBS package
    uses: ./.github/workflows/obs.yaml
    secrets: inherit
    with:
      obs_project: ${{ vars.OBS_PROJECT_ROLLING }}