name: Continous Delivery to SUSE OBS Release Project
concurrency: cd-obs-${{ github.ref }}
on:
  release:
    types: [published]

jobs:
  obs-cd:
    name: Update OBS package
    uses: ./.github/workflows/obs.yaml
    secrets: inherit
    with:
      obs_project: ${{ vars.OBS_PROJECT_STABLE }}
      is_release: true


    